[package]
name = "web-api"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
serde = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
axum = "0.8"
tracing = "0.1"
tracing-subscriber = "0.3"
